### ISSUE TITLE
Ubuntu 22.04 - gnome 42.4 - update to latest version - cannot run

### ISSUE THREAD

**Issue by slawekmikula** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#12] opened 2022-11-12 13:25 UTC
Error during initialization. Previous installed and upgraded to newest. 

Error code:
`Expected type string for argument 'schema_id' but got type undefined`

syslog error:
`Nov 12 14:16:17 Latitude-E5450 gnome-shell[680268]: JS ERROR: Extension ssh-quick-connect@ibrokemy.computer: Error: Expected type string for argument 'schema_id' but got type undefined#012getSettings@resource:///org/gnome/shell/misc/extensionUtils.js:207:34#012_init@/home/xxx/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:28:36#012ButtonBox@resource:///org/gnome/shell/ui/panelMenu.js:11:1#012PanelMenuButton@resource:///org/gnome/shell/ui/panelMenu.js:97:4#012SSHQuickConnect@/home/xxx/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:23:23#012enable@/home/xxx/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:207:15#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:640:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:615:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:646:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:666:14#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:298:22#012start@resource:///org/gnome/shell/ui/main.js:175:5#012@resource:///org/gnome/shell/ui/init.js:6:17
`

**Comment by ibrokemycomputer** [comment] 2022-11-12 15:21
Duplicate of #11

**Closed by ibrokemycomputer** 2022-11-12 15:21 UTC
